version: 2
executorType: docker
containerInfo:
  - image: golang:1.8
stages:
  build:
    workDir: /go/src/github.com/danackerson/digitalocean
    steps:
      - type: checkout
      - type: shell
        command: |
          set -eu
          go get -t -d -v ./...
          ./set_env.sh
          go run do.go
