debug = false
checkNewVersion = true
logLevel = "INFO"
defaultEntryPoints = ["http", "https", "ws", "wss"]

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "ackerson.de"

[entryPoints]
  [entrypoints.dashboard]
    address=":8443"
  [entrypoints.api]
    address=":8442"
  [api]
    entrypoint="api"
    [api.statistics]

  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.redirect]
    regex = "^https://www.(.*)"
    replacement = "https://$1"
    [entryPoints.https.tls]

# These file entries setup the API server as backend &
# the Monitoring Dashboard as frontend
[file]
  [backends]
    [backends.api]
      [backends.api.servers.api]
        url = "http://127.0.0.1:8442"

  [frontends]
    [frontends.monitor]
      entrypoints = ["dashboard"]
      basicAuth = ["admin:$apr1$Sy/ApXHY$fVtWyeyllJ5KvbENX1mgd/"]
      backend = "api"
        [frontends.monitor.routes.monitor]
        rule = "Host:monitor.ackerson.de"

[acme]
email = "dan@ackerson.de"
storage = "acme.json"
entryPoint = "https"
[acme.httpChallenge]
  entryPoint = "http"
[acme.dnsChallenge]
  provider = "digitalocean"
  delayBeforeCheck = 0

[[acme.domains]]
  main = "ackerson.de"
  sans = ["www.ackerson.de", "battlefleet.ackerson.de"]
[[acme.domains]]
  main = "battlefleet.online"
  sans = ["www.battlefleet.online", "battlefleet.online"]
