debug = false
checkNewVersion = true
logLevel = "INFO"
defaultEntryPoints = ["http", "https", "ws", "wss"]

[web]
address = ":8443"
readOnly = true
  [web.auth.basic]
  users = ["admin:$apr1$Sy/ApXHY$fVtWyeyllJ5KvbENX1mgd/"]

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "ackerson.de"

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.redirect]
    regex = "^https://www.(.*)"
    replacement = "https://$1"
    [entryPoints.https.tls]

[acme]
email = "dan@ackerson.de"
storage = "acme.json"
entryPoint = "https"
dnsProvider = "digitalocean"

[[acme.domains]]
  main = "ackerson.de"
  sans = ["www.ackerson.de", "battlefleet.ackerson.de"]
[[acme.domains]]
  main = "battlefleet.online"
  sans = ["www.battlefleet.online", "battlefleet.online"]
