version: 2
jobs:
  build:
    docker:
      - image: golang:1.8
    working_directory: /go/src/github.com/danackerson/digitalocean
    steps:
      - checkout
      - deploy:
          name: Setup new server at Digital Ocean
          command: |
            set -eu
            go get -t -d -v ./...
            ./set_env.sh
            go run do.go -fn=createNewServer
  
