version: 2
jobs:
  build:
    docker:
      - image: golang:1.9
    working_directory: /go/src/github.com/danackerson/digitalocean
    steps:
      - checkout
      - add-ssh-keys:
          fingerprints:
            - "93:c4:61:21:a6:82:d8:6d:4f:73:11:79:37:23:83:07"
      - run:
          name: Start ssh-agent
          command: |
            ssh-agent -s > ~/.ssh_agent_conf
            source ~/.ssh_agent_conf
            for _k in $(ls ${HOME}/.ssh/id_*); do
              ssh-add ${_k} || true
            done

      - run:
          name: Disable Digital Ocean firewall for deploy
          command: |
            curl -s https://raw.githubusercontent.com/danackerson/digitalocean/master/utils/disableFW.sh | sh

      - deploy:
          name: Setup new server at Digital Ocean
          command: |
            go get -t -d -v ./...
            ./set_env.sh
            go run do.go -fn=createNewServer
            source /tmp/new_digital_ocean_droplet_params

            if [[ "$NEW_SERVER_IPV4" ]]; then
              if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
                go run do.go -fn=updateDNS -dropletID=$NEW_DROPLET_ID
              fi

              apt-get update && apt-get -y install jq
              curl -fsS https://raw.githubusercontent.com/danackerson/digitalocean/master/utils/disableFW.sh | bash

              export TRAEFIK_DIR=/home/ackersond/traefik
              export DEPLOY_CONNECT="ssh -o StrictHostKeyChecking=no ackersond@$NEW_SERVER_IPV4"
              $DEPLOY_CONNECT mkdir -p $TRAEFIK_DIR/logs
              $DEPLOY_CONNECT touch $TRAEFIK_DIR/acme.json
              $DEPLOY_CONNECT chmod 600 $TRAEFIK_DIR/acme.json
              scp -o StrictHostKeyChecking=no $PWD/traefik.toml ackersond@$NEW_SERVER_IPV4:$TRAEFIK_DIR/

              $DEPLOY_CONNECT docker network create web || true
              $DEPLOY_CONNECT docker rm -f traefik || true
              $DEPLOY_CONNECT docker run -d --restart=always --network='web' \
                --label='traefik.frontend.rule=Host:monitor.ackerson.de' \
                -v /var/run/docker.sock:/var/run/docker.sock \
                -v $TRAEFIK_DIR/traefik.toml:/traefik.toml \
                -v $TRAEFIK_DIR/logs:/tmp \
                -v $TRAEFIK_DIR/acme.json:/acme.json \
                -e DO_AUTH_TOKEN=$digitalOceanToken \
                -p 8443:8443 -p 80:80 -p 443:443 \
                --name traefik traefik:1.5

              curl --user ${CIRCLE_API_TOKEN}: \
                --data build_parameters[DEPLOY_SERVER_IP]=$NEW_SERVER_IPV4 \
                https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/ackerson.de-go/tree/master
            fi

      - run:
          name: Reenable Digital Ocean firewall
          command: |
             curl -fsS https://raw.githubusercontent.com/danackerson/digitalocean/master/utils/reenableFW.sh | bash
          when: always
