version: 2
jobs:
  build:
    docker:
      - image: golang:1.8
    working_directory: /go/src/github.com/danackerson/digitalocean
    steps:
      - checkout
      - add-ssh-keys:
          name: Load SSH key
          fingerprints:
            - "93:c4:61:21:a6:82:d8:6d:4f:73:11:79:37:23:83:07"
      - run:
          name: Start ssh-agent
          command: |
            ssh-agent -s > ~/.ssh_agent_conf
            source ~/.ssh_agent_conf
            for _k in $(ls ${HOME}/.ssh/id_*); do
              ssh-add ${_k} || true
            done

      - deploy:
          name: Setup new server at Digital Ocean
          command: |
            set -eu
            go get -t -d -v ./...
            ./set_env.sh
            go run do.go -fn=createNewServer
            source /tmp/new_digital_ocean_droplet_params
            echo "IPV4 of new server: $NEW_SERVER_IPV4"
            if [ "$NEW_SERVER_IPV4" ]; then
              curl --user ${CIRCLE_API_TOKEN}: \
                --data build_parameters[DEPLOY_SERVER_IP]=$NEW_SERVER_IPV4 \
                https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/ackerson.de-go/tree/master
              curl --user ${CIRCLE_API_TOKEN}: \
                --data build_parameters[DEPLOY_SERVER_IP]=$NEW_SERVER_IPV4 \
                https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/bender-slackbot/tree/master
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                go run do.go -fn=updateDNS -dropletID=$NEW_DROPLET_ID
                sleep 120 # setting up Docker Remote Engine on CircleCI 2 takes **forever** :(

                source ~/.ssh_agent_conf

                export DEPLOY_CONNECT="ssh -o StrictHostKeyChecking=no ackersond@$NEW_SERVER_IPV4"
                $DEPLOY_CONNECT docker run -d --name letsencrypt --volumes-from ackerson.de quay.io/letsencrypt/letsencrypt certonly --non-interactive --text --agree-tos --webroot --no-eff-email --webroot-path /app/public -m dan@ackerson.de -d ackerson.de
                $DEPLOY_CONNECT sleep 30 # wait for letsencrypt to verify ackerson.de and generate SSL cert
                $DEPLOY_CONNECT docker cp letsencrypt:/etc/letsencrypt/ ./letsencrypt
                $DEPLOY_CONNECT sudo cp ./letsencrypt/archive/ackerson.de/fullchain1.pem /home/ackersond/certs/server.pem
                $DEPLOY_CONNECT sudo cp ./letsencrypt/archive/ackerson.de/privkey1.pem /home/ackersond/certs/server.key
                $DEPLOY_CONNECT docker rm -f letsencrypt && docker restart ackerson.de
              fi
            fi
