version: 2
jobs:
  build:
    docker:
      - image: golang:1.9
    working_directory: /go/src/github.com/danackerson/digitalocean
    steps:
      - checkout
      - add-ssh-keys:
          name: Load SSH key
          fingerprints:
            - "93:c4:61:21:a6:82:d8:6d:4f:73:11:79:37:23:83:07"
      - run:
          name: Start ssh-agent
          command: |
            ssh-agent -s > ~/.ssh_agent_conf
            source ~/.ssh_agent_conf
            for _k in $(ls ${HOME}/.ssh/id_*); do
              ssh-add ${_k} || true
            done

      - deploy:
          name: Setup new server at Digital Ocean
          command: |
            set -eu
            go get -t -d -v ./...
            ./set_env.sh
            go run do.go -fn=createNewServer
            source /tmp/new_digital_ocean_droplet_params
            echo "IPV4 of new server: $NEW_SERVER_IPV4"
            if [ "$NEW_SERVER_IPV4" ]; then
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                go run do.go -fn=updateDNS -dropletID=$NEW_DROPLET_ID
              fi

              curl --user ${CIRCLE_API_TOKEN}: \
                --data build_parameters[DEPLOY_SERVER_IP]=$NEW_SERVER_IPV4 \
                https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/ackerson.de-go/tree/master
              echo
            fi
