name: Deploy DigitalOcean Droplet

on:
  push:
    branches: [ nope ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Build application
        env:
          CTX_DIGITALOCEAN_DROPLET_PROXY_TOKEN: ${{ secrets.CTX_DIGITALOCEAN_DROPLET_PROXY_TOKEN }}
          CTX_DIGITALOCEAN_FIREWALL: ${{ secrets.CTX_DIGITALOCEAN_FIREWALL }}
          CTX_SSH_DEPLOY_FINGERPRINT: ${{ secrets.CTX_SSH_DEPLOY_FINGERPRINT }}
          CTX_RASPBERRYPI_SSH_PRIVKEY: "${{ secrets.CTX_RASPBERRYPI_SSH_PRIVKEY }}"
        run: |
          go get -t -d -v ./...
          go build do.go

          envsubst < do_ubuntu_userdata.sh > digitalocean_ubuntu_userdata.sh
          mkdir ~/.ssh
          ./do -fn=createNewServer

          source /tmp/new_digital_ocean_droplet_params
          public_ip_address=$(curl -s https://checkip.amazonaws.com)
          echo "This instance is @ ${public_ip_address}"

          ./do -fn=firewallSSH -allow=true -ip=$public_ip_address

          sleep 20

          scp -o StrictHostKeyChecking=no go.sum root@$NEW_SERVER_IPV4:~/
          ssh root@$NEW_SERVER_IPV4 << EOF
            scp -o StrictHostKeyChecking=no go.sum ubuntu@[${{ secrets.CTX_IPV6_MASTER_HOME }}]:~/
            ssh ubuntu@${{ secrets.CTX_IPV6_MASTER_HOME }} ls -lrt
          EOF

          # Cleanup TODO: put in if: always() block!
          ./do -fn=firewallSSH -allow=false -ip=$public_ip_address
          ./do -fn=deleteServer -dropletID=$NEW_DROPLET_ID -keyID=$NEW_SSH_KEY_ID
          rm digitalocean_ubuntu_userdata.sh ~/.ssh/id_rsa /tmp/new_digital_ocean_droplet_params
