name: Deploy DigitalOcean Droplet

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Build application and docker image
        env:
          CTX_DIGITALOCEAN_DROPLET_PROXY_TOKEN: ${{ secrets.CTX_DIGITALOCEAN_DROPLET_PROXY_TOKEN }}
          CTX_DIGITALOCEAN_FIREWALL: ${{ secrets.CTX_DIGITALOCEAN_FIREWALL }}
          CTX_SSH_DEPLOY_FINGERPRINT: ${{ secrets.CTX_SSH_DEPLOY_FINGERPRINT }}
          CTX_RASPBERRYPI_SSH_PRIVKEY: ${{ secrets.CTX_RASPBERRYPI_SSH_PRIVKEY }}
        run: |
          go get -t -d -v ./...

          go build do.go

          envsubst < do_ubuntu_userdata.sh

          ./do -fn=createNewServer

          source /tmp/new_digital_ocean_droplet_params

          ./do -ipAddr

          ssh root@$NEW_SERVER_IPV4 ping rabbit.ackerson.de -c 5

          ./do -ipSubr

          ./do -fn=deleteServer -dropletID=$NEW_DROPLET_ID

          rm do_ubuntu_userdata.sh